/**
 * VIBENICITY BUILD ENGINE - STAGE 6: DATABASE MANAGER
 */

const fs = require('fs-extra');
const path = require('path');
const chalk = require('chalk');
const config = require('../config/config');

class DatabaseManager {
    constructor() {
        this.databasePath = path.join(__dirname, '..', config.paths.vocabularyDatabase);
        this.pendingPath = path.join(__dirname, '..', config.paths.pendingTerms);
        this.processedPath = path.join(__dirname, '..', config.paths.processedTerms);
        this.database = null;
    }

    async loadDatabase() {
        try {
            const content = await fs.readFile(this.databasePath, 'utf8');
            const match = content.match(/const culturalVocabularyMaster = ({[\s\S]*});/);
            if (match) {
                this.database = eval(`(${match[1]})`);
                return this.database;
            }
            throw new Error('Could not parse database');
        } catch (error) {
            console.error(chalk.red(`Failed to load database: ${error.message}`));
            return null;
        }
    }

    async savePendingTerms(validatedTerms) {
        console.log(chalk.blue(`\n💾 SAVING PENDING TERMS`));
        
        const pending = validatedTerms.filter(t => 
            t.validation && t.validation.passed && !t.error
        );

        const data = {
            metadata: {
                totalPending: pending.length,
                lastUpdated: new Date().toISOString(),
                version: '1.0'
            },
            terms: pending
        };

        await fs.writeJSON(this.pendingPath, data, { spaces: 2 });
        console.log(chalk.green(`✅ Saved ${pending.length} terms to pending_terms.json\n`));
        
        return pending;
    }

    async mergeApprovedTerms(approvedTermsArray) {
        console.log(chalk.blue(`\n🔗 MERGING APPROVED TERMS`));
        
        await this.createBackup();
        await this.loadDatabase();

        let addedCount = 0;
        for (const term of approvedTermsArray) {
            const category = term.category;
            
            if (!this.database[category]) {
                this.database[category] = [];
            }

            const exists = this.database[category].some(t => 
                t.term.toLowerCase() === term.term.toLowerCase()
            );

            if (!exists) {
                this.database[category].push(term);
                addedCount++;
            }
        }

        this.updateMetadata(addedCount);
        this.sortDatabase();

        const newContent = this.generateDatabaseFile();
        await fs.writeFile(this.databasePath, newContent, 'utf8');

        console.log(chalk.green(`✅ Merged ${addedCount} new terms into database\n`));
        return addedCount;
    }

    async createBackup() {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const backupDir = path.join(__dirname, '..', config.paths.backups);
        await fs.ensureDir(backupDir);
        
        const backupPath = path.join(backupDir, `vocabulary-backup-${timestamp}.js`);
        await fs.copy(this.databasePath, backupPath);
        
        console.log(chalk.gray(`  📁 Backup created: ${path.basename(backupPath)}`));
    }

    updateMetadata(newTermsCount) {
        this.database.metadata.totalTerms += newTermsCount;
        this.database.metadata.lastUpdated = new Date().toISOString().split('T')[0];
        const [major, minor] = this.database.metadata.version.split('.');
        this.database.metadata.version = `${major}.${parseInt(minor) + 1}`;
    }

    sortDatabase() {
        for (const category in this.database) {
            if (Array.isArray(this.database[category])) {
                this.database[category].sort((a, b) => a.term.localeCompare(b.term));
            }
        }
    }

    generateDatabaseFile() {
        return `/**
 * VIBENICITY Cultural Vocabulary Master Database
 * Version: ${this.database.metadata.version}
 * Last Updated: ${this.database.metadata.lastUpdated}
 * Total Terms: ${this.database.metadata.totalTerms}
 * 
 * AUTO-GENERATED BY BUILD ENGINE
 */

const culturalVocabularyMaster = ${JSON.stringify(this.database, null, 4)};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = culturalVocabularyMaster;
}
`;
    }
}

module.exports = DatabaseManager;
